services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest_app
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
