# Generated by Django 5.1.3 on 2024-11-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, unique=True)),
                ('born_date', models.CharField(max_length=50)),
                ('born_location', models.CharField(max_length=150)),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=300)),
                ('quote', models.CharField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.author')),
            ],
        ),
    ]
